name: app_flutter
description: App Flutter que consome a API FastAPI

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
